### ISSUE TITLE
howto install it on MANJARO

### ISSUE THREAD

**Issue by sl5net** [slacka/WoeUSB#286]
## Good Habit Checklist for Issue Reporting
Checkout [Mastering Markdown · GitHub Guides](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) if you need help on the GitHub-flavored Markdown syntax.  You may remove sections and contents that don't apply.

* [x] I've searched the issue tracker and is pretty sure that there's no duplicate issue already filed
* [ ] I've built the latest development snapshot using the instructions in README and verified that the issue can still be reproduced (for bug reports)

## Issue Reproduce Instructions
sudo add-apt-repository ppa:nilarimogard/webupd8
sudo apt update
sudo apt install woeusb

## Current Behavior
add-apt not found

## Info of My Environment
 5.3.8-3-MANJARO #1 SMP PREEMPT Sun Nov 3 14:19:23 UTC 2019 x86_64 GNU/Linux

**Comment by kazuyanakamura** [comment]
The problem is you're trying to run `apt` on a distribution not based on Ubuntu or Deban. `apt` only exists in Debian and Ubuntu based distributions, and Manjaro is based on Arch Linux.

The author does actually point you to the `woeusb-git` AUR package. Use your preferred AUR helper(I think `pamac` is the default on Manjaro) and install it.

More information here:
https://wiki.manjaro.org/index.php?title=Pamac

**Comment by sl5net** [comment]
pamac build woeusb
