### ISSUE TITLE
Dependencies problem on Installing on Ubuntu 20.04

### ISSUE THREAD

**Issue by aasril** [slacka/WoeUSB#319]
I tried both with deb packages from WepUpd8 PPA and built it from source. I ended up with dependencies issues with these two packages:
 - libwxgtk2.8-dev
 - libwxgtk3.0-dev

The error message:
> The following packages have unmet dependencies:
> woeusb : Depends: libwxgtk3.0-0v5 (>= 3.0.4+dfsg) but it is not installable
> E: Unable to correct problems, you have held broken packages.

When I search for libwxgtk3, I found these packages instead:
 - libwxgtk3.0-gtk3-0v5
 - libwxgtk3.0-gtk3-dev

There is [similar issue](https://github.com/slacka/WoeUSB/issues/159) regarding unsatisfied dependencies with an older version of Ubuntu, but the problematic dependencies are different, though.

**Comment by mikersa** [comment]
same problem

**Comment by aua-style** [comment]
Same problem. Need solution

**Comment by adrian-donraadt** [comment]
same problem.
I tried to install woeusb_3.3.1-1_webupd8_focal0_amd64.deb
it has a dependency error: is not satisfide libwxgtk3.0-0v5 (>=3.0.4+dfsg)
I searched with synaptic but it found libwxgtk3-gtk3-0v5.
found it on https://www.ubuntuupdates.org/package/core/eoan/universe/base/libwxgtk3.0-0v5

I hope that this brings  you a solution

**Comment by Rafal-G** [comment]
@adrian-donraadt that worked, thanks for sharing! Would be nice if the package got fixed, but this is a nice workaround for now.

**Comment by aasril** [comment]
@adrian-donraadt so, it looks like changes in packages' naming is the root of this issue.

I ended up just copying the contents of mounted Windows 10 iso to a newly fat32 formatted USB drive. And it works as a Windows 10 USB installer/recovery drive.

**Comment by Lion-box** [comment]
No @aasril , it is not only a name change.
Wxwidgets apparently dropped all GTK2 related packages in version 3.0.4+dfsg-15 (the one included in Ubuntu 20.04)

_wxwidgets3.0 (3.0.4+dfsg-15) unstable; urgency=medium_

- _Drop GTK2 flavoured packages._
- _debian/patches/upstream-changes-since-3.0.4.patch: Update to include  "Fix mistake in wxDateTime::Tm struct documentation".  Upstream ticket #18534._

**Comment by spuny** [comment]
> same problem.
> I tried to install woeusb_3.3.1-1_webupd8_focal0_amd64.deb
> it has a dependency error: is not satisfide libwxgtk3.0-0v5 (>=3.0.4+dfsg)
> I searched with synaptic but it found libwxgtk3-gtk3-0v5.
> found it on https://www.ubuntuupdates.org/package/core/eoan/universe/base/libwxgtk3.0-0v5
> 
> I hope that this brings you a solution

This workaround is so far only solution to this error. Thanks for it ;)

**Comment by sanmusen404** [comment]
> same problem.
> I tried to install woeusb_3.3.1-1_webupd8_focal0_amd64.deb
> it has a dependency error: is not satisfide libwxgtk3.0-0v5 (>=3.0.4+dfsg)
> I searched with synaptic but it found libwxgtk3-gtk3-0v5.
> found it on https://www.ubuntuupdates.org/package/core/eoan/universe/base/libwxgtk3.

> same problem.
> I tried to install woeusb_3.3.1-1_webupd8_focal0_amd64.deb
> it has a dependency error: is not satisfide libwxgtk3.0-0v5 (>=3.0.4+dfsg)
> I searched with synaptic but it found libwxgtk3-gtk3-0v5.
> found it on https://www.ubuntuupdates.org/package/core/eoan/universe/base/libwxgtk3.0-0v5
> 
> I hope that this brings you a solution

good

**Comment by SuryaDilip** [comment]
> same problem.
> I tried to install woeusb_3.3.1-1_webupd8_focal0_amd64.deb
> it has a dependency error: is not satisfide libwxgtk3.0-0v5 (>=3.0.4+dfsg)
> I searched with synaptic but it found libwxgtk3-gtk3-0v5.
> found it on https://www.ubuntuupdates.org/package/core/eoan/universe/base/libwxgtk3.0-0v5
> 
> I hope that this brings you a solution

@adrian-donraadt Your resolution worked, Thanks a lot.

**Comment by KaKi87** [comment]
It also worked for me, thanks !

**Comment by Bojesen2000** [comment]
I install the one from ubuntu-saftware with no problems.

**Comment by Kyanite393** [comment]
Same

@adrian-donraadt Your work around successfully installed woeusb

**Comment by anikseu** [comment]
Same problem. Worse thing is, when i try to install **libwxgtk3.0-0v5** following error is being encountered: (Ubuntu 20.04) 

```
dpkg: error processing package libwxgtk3.0-0v5:amd64 (--install):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.31-0ubuntu9) ...
Errors were encountered while processing:
 libwxgtk3.0-0v5:amd64

```

**Comment by KaKi87** [comment]
@anikseu When encountering this error, whatever package it is, just run `apt install -f` (aka `--fix-missing`) and the dependencies will be automatically installed and the package will be configured. I still doesn't know why this command isn't just run automatically after a `dpkg -i`... 🤔

**Comment by ghimireadarsh** [comment]
Cloining and following the instructions, works perfectly.

**Comment by BiNh0X** [comment]
> same problem.
> I tried to install woeusb_3.3.1-1_webupd8_focal0_amd64.deb
> it has a dependency error: is not satisfide libwxgtk3.0-0v5 (>=3.0.4+dfsg)
> I searched with synaptic but it found libwxgtk3-gtk3-0v5.
> found it on https://www.ubuntuupdates.org/package/core/eoan/universe/base/libwxgtk3.0-0v5
> 
> I hope that this brings you a solution

Thank you. :*

**Comment by mr-infinitehawk** [comment]
> same problem.
> I tried to install woeusb_3.3.1-1_webupd8_focal0_amd64.deb
> it has a dependency error: is not satisfide libwxgtk3.0-0v5 (>=3.0.4+dfsg
> I searched with synaptic but it found libwxgtk3-gtk3-0v5.
> found it on https://www.ubuntuupdates.org/package/core/eoan/universe/base/libwxgtk3.0-0v5
> 
> I hope that this brings you a solution

TY It works

**Comment by pichaosdev** [comment]
thanks  @adrian-donraadt !

**Comment by Saagar-afk** [comment]
This worked for me:
sudo apt-get install libwxbase3.0-0v5

**Comment by safwenHafsawy** [comment]
> same problem.
> I tried to install woeusb_3.3.1-1_webupd8_focal0_amd64.deb
> it has a dependency error: is not satisfide libwxgtk3.0-0v5 (>=3.0.4+dfsg)
> I searched with synaptic but it found libwxgtk3-gtk3-0v5.
> found it on https://www.ubuntuupdates.org/package/core/eoan/universe/base/libwxgtk3.0-0v5
> 
> I hope that this brings you a solution

thank you so much a true life saver

**Comment by MaximMukhametov** [comment]
It helped me : 
`sudo apt install libwxgtk3.0-gtk3-0v5`

**Comment by Vinaum8** [comment]
i follow this tutorial (https://www.cyberciti.biz/faq/create-a-bootable-windows-10-usb-in-linux/) and work fine in ubuntu 20.04

**Comment by aasril** [comment]
I ran `git pull` and reran the install steps as told in the README and it finished with no errors this time.

**Comment by alirezaismyname** [comment]
Hi. This may help:
https://www.how2shout.com/linux/how-to-install-woeusb-on-ubuntu-20-04-lts/

**Comment by RajashekarY** [comment]
> same problem.
> I tried to install woeusb_3.3.1-1_webupd8_focal0_amd64.deb
> it has a dependency error: is not satisfide libwxgtk3.0-0v5 (>=3.0.4+dfsg)
> I searched with synaptic but it found libwxgtk3-gtk3-0v5.
> found it on https://www.ubuntuupdates.org/package/core/eoan/universe/base/libwxgtk3.0-0v5
> 
> I hope that this brings you a solution

https://www.ubuntuupdates.org/package/core/bionic/universe/base/libwxgtk3.0-0v5
that link expired

**Comment by gcclinux** [comment]
I've just used the following installing from bionic on my 20.04.01

1) Download package:
http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu/pool/main/w/woeusb/woeusb_3.3.1-1~webupd8~focal0_amd64.deb

2) Add this source to your config:
https://packages.ubuntu.com/bionic/amd64/libwxgtk3.0-0v5/download

3) Once configured just install the package like this and it will install all dependencies.
$ sudo apt install <PATH>/woeusb_3.3.1-1~webupd8~focal0_amd64.deb

All works without any issues.

**Comment by Lumipyry** [comment]
I had a working WoeUSB but I cleaned up my computer and installed brand new Kubuntu 20.10.

When I tried to install WoeUSB again, I ran in to trouble as most of You. 

- I tried snap from snapcraft.io. It installed but did not open.
- I tried GitHub project page, but got confused with the changes (at October 25th the project has moved to https://github.com   /WoeUSB). The first version of WoeUSB in the new page list is something I don't understand. 
- I tried .deb package but dependencies were missing although I had downloaded all the old dependencies.
(Seems that @gcclinux found the missing **libwxgtk3.0-0v5** dependency.)

When I saw @Vinaum8's comment, I remembered that  previously I installed WoeUSB same way as he did. However, since WoeUSB  has moved to new page these instructions have to be modified accordingly. (The original WoeUSB is there under name WoeUSB-frontend-wxgtk).

Finally from the new WoeUSB project page I installed WoeUSB-ng (works fine in Kubuntu 20.10) with following easy steps (for Ubuntu):

Install dependencies:

$ sudo apt install git p7zip-full python3-pip python3-wxgtk4.0 

Install WoeUSB-ng:

$ sudo pip3 install WoeUSB-ng

**Comment by JEEVA-JB** [comment]
**woeusb : Depends: libwxgtk3.0-0v5 (>= 3.0.4+dfsg) but it is not installable..**

Woeusb error while installing in Ubuntu cased due to the unavailability of libwxgtk3.0-0v5 package 
we can install it from https://www.ubuntuupdates.org/package/core/bionic/universe/base/libwxgtk3.0-0v5 
(or) direct link
 
**32bit -** [click here to download](http://security.ubuntu.com/ubuntu/pool/universe/w/wxwidgets3.0/libwxgtk3.0-0v5_3.0.4+dfsg-3_i386.deb)
then.

`$ sudo apt install ./libwxgtk3.0-0v5_3.0.4+dfsg-3_i386.deb` in Download directory

**64bit -** [click here to download](http://security.ubuntu.com/ubuntu/pool/universe/w/wxwidgets3.0/libwxgtk3.0-0v5_3.0.4+dfsg-3_amd64.deb)
then.

`$ sudo apt install ./libwxgtk3.0-0v5_3.0.4+dfsg-3_amd64.deb` in Download directory
![Screenshot at 2020-07-28 08-18-54](https://user-images.githubusercontent.com/67570918/99896914-03408a80-2cbb-11eb-8270-eb3031f31428.png)



after installing the above package follow the below commands to install woeusb  

`$ sudo add-apt-repository ppa:nilarimogard/webupd8`
`$ sudo apt update`
`$ sudo apt install woeusb`

**Comment by baclavan** [comment]
> This worked for me:
> sudo apt-get install libwxbase3.0-0v5

thanks, it helped me :D

**Comment by baclavan** [comment]
> This worked for me:
> sudo apt-get install libwxbase3.0-0v5

Thank a lots !

**Comment by bachtrantnb** [comment]
> ### **woeusb : Depends: libwxgtk3.0-0v5 (>= 3.0.4+dfsg) but it is not installable..**
> 
> ![Screenshot at 2020-07-28 08-18-54](https://user-images.githubusercontent.com/67570918/99896914-03408a80-2cbb-11eb-8270-eb3031f31428.png)
> 
> Woeusb error while installing in Ubuntu cased due to the unavailability of libwxgtk3.0-0v5 package
> we can install it from https://www.ubuntuupdates.org/package/core/bionic/universe/base/libwxgtk3.0-0v5
> (or) direct link below
> 
> **32bit -** [click here to download](http://security.ubuntu.com/ubuntu/pool/universe/w/wxwidgets3.0/libwxgtk3.0-0v5_3.0.4+dfsg-3_i386.deb)
> then.
> 
> `$ sudo apt install ./libwxgtk3.0-0v5_3.0.4+dfsg-3_i386.deb` in Download directory
> 
> **64bit -** [click here to download](http://security.ubuntu.com/ubuntu/pool/universe/w/wxwidgets3.0/libwxgtk3.0-0v5_3.0.4+dfsg-3_amd64.deb)
> then.
> 
> `$ sudo apt install ./libwxgtk3.0-0v5_3.0.4+dfsg-3_amd64.deb` in Download directory
> 
> after installing the above package follow the below commands to install woeusb
> 
> `$ sudo add-apt-repository ppa:nilarimogard/webupd8`
> `$ sudo apt update`
> `$ sudo apt install woeusb`

nice! Thank a lots bro
